### ISSUE TITLE
STAMP DSpot Reports is not showing reports when DSpot is not executed by the plugin

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/stamp-ci#11]
I've configured STAMP DSpot Reports to visualize the DSpot results after each build and DSpot run. DSpot is executed using a build script in a Freestyle project.
STAMP DSpot Reports is configured as shown in picture:
![image](https://user-images.githubusercontent.com/3658315/55177232-09e3cb00-5183-11e9-9dae-093502cc6982.png)
However, the execution ends successfully without adding an DSpot Reports entry in job run, reporting in console:
`DSpot report already configured from Buld step. skipping post build step config.Finished: SUCCESS`
but the DSpot Build plugin wasn't used to run DSpot and therefore that report wasn't configured during the build phase.
According to the documentation, if DSpot is executed using the Maven interface in a build script (or using the Maven plugin for Jenkins), and we want to visualize the report using this DSpot Reports plugin, we should just add it as a post-build step, as I did, but it seems to detect that the report was created by the DSpot plugin for Jenkins, which is actually not used in job configuration.
Am I doing something wrong?
Thanks
Yosu

**Comment by danzone** [comment]
Dear Yosu, thanks a lot for your feedback, we're going to investigate about this issue.

**Comment by jesus-gorronogoitia** [comment]
Ciao @danzone 
I am resuming this issue. Could you managed to have a look on it? Is there any new update of this plugin to visualize the DSpot results? Please, keep me informed. Grazie mille.

**Comment by danzone** [comment]
¡Hola @jesus-gorronogoitia ! @nicolabertazzo  is working on it (actually I think he almost completed and released the new version of the plugin). This week we'll have an internal STAMP ENG meeting, and I will check this.

**Comment by jesus-gorronogoitia** [comment]
Ciao
Grazie. I will pull this repository,  build the plugins and test the DSpot one. I'll keep you informed.

**Comment by jesus-gorronogoitia** [comment]
Ciao @danzone, @nicolabertazzo 
I've just compiled dspot-jenkins-plugin from latest pull, installed it into Jenkins and tested again as a post-build task, but the plugin does not show DSpot results (obtained in a build step using direct DSpot execution with Maven, but not your plugin), showing the same message in logs I showed you above:
`DSpot report already configured from Build step. skipping post build step config.Finished: SUCCESS`

**Comment by nicolabertazzo** [comment]
Hi @jesus-gorronogoitia,
i fixed the bug and merge the commit.
Now if you
- create a jenkins freestyle job
- add a build step that execute dspot (with java or maven)
- add a post build with STAMP Dspot Reports

It works.
I tested it with dhell in stamp ci infrastructure.

Nicola
